### ISSUE TITLE
~exports seems to fail prevent meteor restart

### ISSUE THREAD

**Issue by Rebolon** [TimHeckel/meteor-webshot#1]
Hi,

i tried your package, but even with public/~exports folder, meteor always restart app when new file is created.
Test is simple : start meteor with 
   #>meteor
do a 
   #> touch public/~exports/myImage.png
see meteor logs : it restarts

any idea ?

**Comment by TimHeckel** [comment]
Rebolon -- it needs to be `exports~` with the `~` at the _end_ of the directory name :)

**Comment by Rebolon** [comment]
ok, thanks a lot for information
